name: Build Android APK

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
     - name: Setup Node.js
  uses: actions/setup-node@v4
  with:
    node-version: "22.x"
    check-latest: true

      - run: npm install

      - run: npm run build

      - run: npm install @capacitor/core @capacitor/cli @capacitor/android

      - run: npx cap sync android

      - uses: android-actions/setup-android@v3

      - name: Build APK
        run: |
          cd android
          chmod +x gradlew
          ./gradlew assembleDebug

      - uses: actions/upload-artifact@v4
        with:
          name: AlQaahir-APK
          path: android/app/build/outputs/apk/debug/app-debug.apk
