name: Build Android

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      # إنشاء مجلد وهمي سريع حتى لا يعترض نظام المزامنة
      - name: Create dummy dist
        run: mkdir -p dist && touch dist/index.html

      # مزامنة وحقن رابط الموقع الحي داخل إعدادات الأندرويد الأصلية
      - name: Capacitor Sync
        run: npx cap sync android

      # استخدام إصدار جافا 21 المتوافق مع تطبيقك
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Grant Execute Permission for Gradle
        run: chmod +x android/gradlew

      - name: Build Android APK
        run: |
          cd android
          ./gradlew assembleRelease

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: android/app/build/outputs/apk/debug/app-debug.apk
